@echo off
echo Starting Stock Market Aggregator...
start /B python app.py
echo Application started on http://localhost:8080
timeout /t 3 /nobreak > nul
echo Testing application...
curl http://localhost:8080 2>nul || echo Application is starting up...